({
    doInit: function (component, event, helper) {
        const iconGroups = [
            {
                groupName : "Action",
                prefix : "action",
                iconNames : [ 
                    'add_contact', 'add_file', 'add_photo_video', 
                    'add_relationship', 'announcement', 'apex',
                    'approval', 'back', 'bug', 'call', 'canvas',
                    'change_owner', 'change_record_type', 'check',
                    'clone', 'close', 'defer', 'delete',
                    'description', 'dial_in', 'download', 'edit_groups',
                    'edit_relationship', 'edit', 'email', 'fallback',
                    'filter', 'flow', 'follow', 'following', 
                    'freeze_user', 'goal', 'google_news', 'info',
                    'join_group', 'lead_convert', 'leave_group',
                    'log_a_call', 'log_event', 'manage_perm_sets', 'map', 'more', 'new_account',
                    'new_campaign', 'new_case', 'new_child_case', 'new_contact', 'new_event', 'new_group',
                    'new_lead', 'new_note', 'new_notebook', 'new_opportunity', 'new_person_account', 'new_task',
                    'new', 'password_unlock', 'preview', 'priority', 'question_post_action', 'quote',
                    'recall', 'record', 'refresh', 'reject', 'remove_relationship', 'remove',
                    'reset_password', 'script', 'share_file', 'share_link', 'share_poll', 'share_post',
                    'share_thanks', 'share', 'sort', 'submit_for_approval', 'update_status',
                    'update', 'upload', 'user_activation', 'user', 'view_relationship', 'web_link' ]
            },
            {
                groupName : "Custom",
                prefix : "custom",
                iconSize : "large",
                iconNames : (function() {
                    let customIcons = [];
                    for (let i = 0; i < helper.NUM_CUSTOM_ICONS; i++) {
                        customIcons.push('custom' + (i+1));
                    }
                    return customIcons;
                })()
            },
            {
                groupName : "Document Type",
                prefix : "doctype",
                iconSize : "large",
                iconNames : [
                    'ai', 'attachment', 'audio', 'box_notes', 'csv', 
                    'eps', 'excel', 'exe', 'flash', 'folder', 
                    'gdoc', 'gdocs', 'gform', 'gpres', 'gsheet', 
                    'html', 'image', 'keynote', 'library_folder', 'link', 
                    'mp4', 'overlay', 'pack', 'pages', 'pdf', 
                    'ppt', 'psd', 'quip_doc', 'quip_sheet', 'quip_slide',
                    'rtf', 'slide', 'stypi', 'txt', 'unknown', 
                    'video', 'visio', 'webex', 'word', 'xml', 
                    'zip'
                ]
            },
            {
                groupName : "Standard",
                prefix : "standard",
                iconSize : "large",
                iconNames : [
                    "account","action_list_component","actions_and_buttons","activations","address",
                    "agent_session","all","announcement","answer_best","answer_private",
                    "answer_public","apex","apex_plugin","app","approval",
                    "apps","apps_admin","article","asset_action","asset_action_source",
                    "asset_downtime_period","asset_object","asset_relationship","asset_state_period","assigned_resource",
                    "assignment","avatar","avatar_loading","bot","bot_training",
                    "branch_merge","brand","business_hours","buyer_account","buyer_group",
                    "calibration","call","call_coaching","call_history","campaign",
                    "campaign_members","cancel_checkout","canvas","carousel","case",
                    "case_change_status","case_comment","case_email","case_log_a_call","case_milestone",
                    "case_transcript","case_wrap_up","catalog","category","channel_program_history",
                    "channel_program_levels","channel_program_members","channel_programs","chart","choice",
                    "client","cms","coaching","code_playground","collection_variable",
                    "connected_apps","constant","contact","contact_list","contact_request",
                    "contract","contract_line_item","currency","currency_input","custom",
                    "custom_notification","customer_360","customer_lifecycle_analytics","customer_portal_users","customers",
                    "dashboard","dashboard_ea","data_integration_hub","data_model","data_streams",
                    "datadotcom","dataset","date_input","date_time","decision",
                    "default","delegated_account","display_rich_text","display_text","document",
                    "drafts","dynamic_record_choice","education","einstein_replies","email",
                    "email_chatter","employee","employee_asset","employee_contact","employee_job",
                    "employee_job_position","employee_organization","empty","endorsement","entitlement",
                    "entitlement_policy","entitlement_process","entitlement_template","entity","entity_milestone",
                    "environment_hub","event","events","expense","expense_report",
                    "expense_report_entry","feed","feedback","file","filter",
                    "first_non_empty","flow","folder","forecasts","formula",
                    "fulfillment_order","generic_loading","global_constant","goals","group_loading",
                    "groups","hierarchy","high_velocity_sales","home","household",
                    "individual","insights","instore_locations","investment_account","invocable_action",
                    "iot_context","iot_orchestrations","javascript_button","job_family","job_position",
                    "job_profile","kanban","knowledge","lead","lead_insights",
                    "lead_list","letterhead","lightning_component","lightning_usage","link",
                    "list_email","live_chat","live_chat_visitor","location","log_a_call",
                    "logging","loop","macros","maintenance_asset","maintenance_plan",
                    "marketing_actions","merge","messaging_conversation","messaging_session","messaging_user",
                    "metrics","multi_picklist","multi_select_checkbox","news","note",
                    "number_input","omni_supervisor","operating_hours","opportunity","opportunity_contact_role",
                    "opportunity_splits","order_item","orders","outcome","output",
                    "partner_fund_allocation","partner_fund_claim","partner_fund_request","partner_marketing_budget","partners",
                    "password","past_chat","people","performance","person_account",
                    "photo","picklist_choice","picklist_type","planogram","poll",
                    "portal","portal_roles","portal_roles_and_subordinates","post","pricebook",
                    "process","product","product_consumed","product_item","product_item_transaction",
                    "product_request","product_request_line_item","product_required","product_transfer","proposition",
                    "question_best","question_feed","queue","quick_text","quip",
                    "quip_sheet","quotes","radio_button","read_receipts","recent",
                    "record","record_create","record_delete","record_lookup","record_update",
                    "recycle_bin","related_list","relationship","reply_text","report",
                    "resource_absence","resource_capacity","resource_preference","resource_skill","return_order",
                    "return_order_line_item","reward","rtc_presence","sales_cadence","sales_cadence_target",
                    "sales_channel","sales_path","sales_value","salesforce_cms","scan_card",
                    "schedule_objective","scheduling_constraint","scheduling_policy","screen","search",
                    "segments","service_appointment","service_appointment_capacity_usage","service_contract","service_crew",
                    "service_crew_member","service_report","service_resource","service_territory","service_territory_location",
                    "service_territory_member","settings","shift","shift_preference","shift_template",
                    "shift_type","shipment","skill","skill_entity","skill_requirement",
                    "sms","snippet","snippets","sobject","sobject_collection",
                    "social","solution","sort","sossession","stage",
                    "stage_collection","steps","store","store_group","story",
                    "strategy","survey","system_and_global_variable","task","task2",
                    "team_member","template","text","text_template","textarea",
                    "textbox","thanks","thanks_loading","timesheet","timesheet_entry",
                    "timeslot","today","topic","topic2","trailhead",
                    "unmatched","user","user_role","variable","visit_templates",
                    "visits","visualforce_page","voice_call","waits","webcart",
                    "work_capacity_limit","work_capacity_usage","work_contract","work_order","work_order_item",
                    "work_plan","work_plan_rule","work_plan_template","work_plan_template_entry","work_queue",
                    "work_step","work_step_template","work_type","work_type_group"  
                ]
            },
            {
                groupName : "Utility",
                prefix : "utility",
                iconNames : [
                    "activity","ad_set","add","adduser","advanced_function",
                    "advertising","agent_session","alert","all","anchor",
                    "animal_and_nature","announcement","answer","answered_twice","apex",
                    "apex_plugin","approval","apps","archive","arrowdown",
                    "arrowup","assignment","attach","automate","away",
                    "back","ban","block_visitor","bold","bookmark",
                    "breadcrumbs","broadcast","brush","bucket","builder",
                    "button_choice","call","campaign","cancel_file_request","cancel_transfer",
                    "capslock","cart","case","cases","center_align_text",
                    "change_owner","change_record_type","chart","chat","check",
                    "checkin","chevrondown","chevronleft","chevronright","chevronup",
                    "choice","classic_interface","clear","clock","close",
                    "collapse_all","collection_variable","color_swatch","comments","company",
                    "component_customization","connected_apps","constant","contact_request","contract",
                    "contract_alt","copy","copy_to_clipboard","crossfilter","currency",
                    "currency_input","custom_apps","cut","dash","database",
                    "datadotcom","date_input","date_time","dayview","delete",
                    "deprecate","description","desktop","desktop_and_phone","desktop_console",
                    "dialing","diamond","dislike","display_rich_text","display_text",
                    "dock_panel","down","download","drag","drag_and_drop",
                    "dynamic_record_choice","edit","edit_form","education","einstein",
                    "email","email_open","emoji","end_call","end_chat",
                    "end_messaging_session","engage","enter","erect_window","error",
                    "event","events","expand","expand_all","expand_alt",
                    "fallback","favorite","feed","file","filter",
                    "filterList","flow","flow_alt","food_and_drink","formula",
                    "forward","forward_up","frozen","fulfillment_order","full_width_view",
                    "global_constant","graph","groups","help","help_center",
                    "hide","hide_mobile","hierarchy","high_velocity_sales","home",
                    "identity","image","in_app_assistant","inbox","incoming_call",
                    "info","info_alt","insert_tag_field","insert_template","inspector_panel",
                    "internal_share","italic","jump_to_bottom","jump_to_top","justify_text",
                    "kanban","keyboard_dismiss","knowledge_base","layers","layout",
                    "leave_conference","left","left_align_text","level_down","level_up",
                    "light_bulb","lightning_extension","lightning_inspector","like","link",
                    "linked","list","listen","live_message","location",
                    "lock","locker_service_api_viewer","locker_service_console","log_a_call","logout",
                    "loop","lower_flag","macros","magicwand","mark_all_as_read",
                    "matrix","merge","merge_field","metrics","minimize_window",
                    "missed_call","money","moneybag","monthlyview","move",
                    "multi_picklist","multi_select_checkbox","muted","new","new_direct_message",
                    "new_window","news","note","notebook","notification",
                    "number_input","office365","offline","offline_cached","omni_channel",
                    "open","open_folder","opened_folder","outbound_call","outcome",
                    "overflow","package","package_org","package_org_beta","page",
                    "palette","password","paste","pause","people",
                    "phone_landscape","phone_portrait","photo","picklist","picklist_choice",
                    "picklist_type","pin","pinned","play","podcast_webinar",
                    "pop_in","power","preview","print","priority",
                    "privately_shared","process","prompt","prompt_edit","push",
                    "puzzle","question","question_mark","questions_and_answers","quick_text",
                    "quip","quotation_marks","quote","radio_button","rating",
                    "reassign","record","record_create","record_delete","record_lookup",
                    "record_update","recurring_exception","recycle_bin_empty","recycle_bin_full","redo",
                    "refresh","relate","reminder","remove_formatting","remove_link",
                    "replace","reply","reply_all","report_issue","reset_password",
                    "resource_absence","resource_capacity","resource_territory","retail_execution","retweet",
                    "ribbon","richtextbulletedlist","richtextindent","richtextnumberedlist","richtextoutdent",
                    "right","right_align_text","rotate","routing_offline","rows",
                    "rules","salesforce1","save","screen","search",
                    "section","send","sentiment_negative","sentiment_neutral","settings",
                    "setup","setup_assistant_guide","setup_modal","share","share_file",
                    "share_mobile","share_post","shield","shift_ui","shopping_bag",
                    "shortcuts","side_list","signpost","skip","skip_back",
                    "skip_forward","slider","smiley_and_people","sms","snippet",
                    "sobject","sobject_collection","socialshare","sort","spinner",
                    "stage","stage_collection","standard_objects","steps","stop",
                    "store","strategy","strikethrough","success","summary",
                    "summarydetail","survey","switch","symbols","sync",
                    "system_and_global_variable","table","table_settings","tablet_landscape","tablet_portrait",
                    "tabset","target","task","text","text_background_color",
                    "text_color","text_template","textarea","textbox","threedots",
                    "threedots_vertical","thunder","tile_card_list","toggle","toggle_panel_bottom",
                    "toggle_panel_left","toggle_panel_right","toggle_panel_top","topic","topic2",
                    "touch_action","tracker","trail","trailhead","travel_and_places",
                    "trending","turn_off_notifications","type","type_tool","undelete",
                    "undeprecate","underline","undo","unlinked","unlock",
                    "unmuted","up","upload","user","user_role",
                    "variable","video","voicemail_drop","volume_high","volume_low",
                    "volume_off","waits","warning","watchlist","weeklyview",
                    "wifi","work_order_type","world","yubi_key","zoomin",
                    "zoomout"
                ]
            }
        ];
        component.set('v.iconGroups', iconGroups);
        component.set('v.iconGroupNames', iconGroups.map(group => group.groupName));
    },
    selectIcon: function (component, event, helper) {
        const selected = event.getSource().get('v.name');
        //console.log(selected);
        component.set('v.selected', selected);
        
        const selectEvent = $A.get("e.c:FlowPicklistIconSelect");
        selectEvent.setParams({
            'iconName'      : selected,
            'picklistValue' : component.get('v.picklistValue')
        });
        selectEvent.fire();
        component.find("overlayLib1").notifyClose();
    }
})